# Generated by Django 3.2 on 2022-06-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Tel',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
